# Site settings
name: 'Sajin M Prasad'
title: 'The Unknown Journey'
description: 'I write about some technology and code here. There are some occasional ramblings as well.'
big_description: "Sajin's blog. Ruby on rails, linux, blog, technology."
baseurl: ""
url: 'https://sajinmp.com'
repo: 'https://github.com/sajinmp/sajinmp.github.io'

# Build settings
markdown: kramdown
highligher: rouge
permalink: /posts/:categories/:title
collections:
  pages:
    permalink: pretty
    output: true
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Author
author:
  image: '/assets/images/sajinmp.jpeg'
  work: 'Backend & Site Reliability'
  company: 'The Mobility Methods LLC'
  location: 'Bangalore, India'
  email: 'sajinprasadkm@gmail.com'
  github: 'https://github.com/sajinmp'
  linkedin: 'https://linkedin.com/in/sajinmp'
  stackoverflow: 'https://stackoverflow.com/users/1713555/sajinmp' 
