# Site settings
name: 'Sajin M Prasad'
title: 'The Path to the Peak'
description: 'A technology blog with a tinge of life mixed within.'
big_description: "A tech blog written by sajinmp (sajin m prasad). Ruby on rails, linux, blog, technology."
baseurl: ""
url: 'http://sajinmp.com'
repo: 'https://github.com/sajinmp/sajinmp.github.io'

# Build settings
markdown: kramdown
highligher: rouge
permalink: /posts/:categories/:title
collections:
  pages:
    permalink: pretty
    output: true
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Author
author:
  image: '/assets/images/sajinmp.jpg'
  work: 'Software Developer'
  company: 'TongueStun'
  location: 'Bangalore, India'
  email: 'sajinprasadkm@gmail.com'
  github: 'https://github.com/sajinmp'
  linkedin: 'https://linkedin.com/in/sajinmp'
  stackoverflow: 'https://stackoverflow.com/users/1713555/sajinmp' 
